### ISSUE TITLE
Tweet only if passed a threshold

### ISSUE THREAD

**Issue by jarad** [dailyerosion/dep#81]
The automated tweeting since Oct 24 basically shows nothing. I assume this is due to the lack of precipitation rather than an incorrect map. Thus, I suggest the automated tweeting be modified to only tweet if there is something to show, e.g. minimum HUC12 soil loss passes a threshold.

**Comment by jarad** [comment]
related to #59

**Comment by akrherz** [comment]
Hi @jarad, thanks for opening this issue.  At a recent DEP team meeting, it was decided to not auto tweet the daily results during the cold season. refs: 37ee1a9b26a
